language: en
pipeline:
- name: kairon.nlu.LLMClassifier
- name: FallbackClassifier
  threshold: 0.3
policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_action_name: action_default_fallback
  core_fallback_threshold: 0.3
