language: en
pipeline:
- name: WhitespaceTokenizer
- model_name: distilbert
  name: LanguageModelFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- epochs: 50
  name: DIETClassifier
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.85
- name: ResponseSelector
  epochs: 100
policies:
- name: MemoizationPolicy
- epochs: 100
  max_history: 5
  name: TEDPolicy
- core_fallback_action_name: "action_default_fallback"
  core_fallback_threshold: 0.70
  enable_fallback_prediction: true
  name: RulePolicy
