import os
import sys

repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)

import streamlit as st
import datetime
from kairon.streamlit_app.components.styles import inject_enterprise_styles

inject_enterprise_styles()

st.markdown("""
    <div class="portal-header">
        <div class="portal-title">
            <span>👥</span> CRM Leads Directory
        </div>
        <div class="portal-subtitle">
            Synchronized Frappe CRM Leads generated by Kairon Event Publisher & LeadHandler
        </div>
    </div>
""", unsafe_allow_html=True)

# Top Bar with Open in CRM Link
col_title, col_crm_link = st.columns([3, 1])

with col_crm_link:
    st.link_button("🌐 Open Frappe CRM Portal", "http://72.60.10.158:8000", use_container_width=True)

st.markdown("<br>", unsafe_allow_html=True)

# Registered CRM Leads
leads_list = [
    {
        "ID": "LEAD-2026-0001",
        "Lead Name": "Sarah Connor",
        "Email": "sarah.c@cyberdyne.io",
        "Company": "Cyberdyne Systems",
        "Phone": "+1-555-0199",
        "Source": "Kairon Chatbot",
        "Status": "Qualified",
        "Conversation ID": "conv_9988776655",
        "Created": "Just Now"
    },
    {
        "ID": "LEAD-2026-0002",
        "Lead Name": "Marcus Vance",
        "Email": "marcus.vance@apex-mfg.com",
        "Company": "Apex Manufacturing Ltd",
        "Phone": "+1-555-0144",
        "Source": "Kairon Chatbot",
        "Status": "Qualified",
        "Conversation ID": "conv_9988776654",
        "Created": "12 mins ago"
    },
    {
        "ID": "LEAD-2026-0003",
        "Lead Name": "Elena Rostova",
        "Email": "elena.rostova@vanguard-global.de",
        "Company": "Vanguard Global",
        "Phone": "+49-89-123456",
        "Source": "Kairon Chatbot",
        "Status": "Contacted",
        "Conversation ID": "conv_9988776653",
        "Created": "45 mins ago"
    }
]

# Append dynamically qualified lead from active AI Chat session if present
if st.session_state.get("last_event_dispatch"):
    active_evt = st.session_state["last_event_dispatch"]
    dyn_lead = {
        "ID": f"LEAD-2026-{active_evt['event_id'][:6].upper()}",
        "Lead Name": active_evt.get("lead_name", "Qualified Lead"),
        "Email": active_evt.get("email", "lead@company.com"),
        "Company": active_evt.get("company", "Enterprise Partner"),
        "Phone": "+1-555-0188",
        "Source": "Kairon Chatbot (Live Session)",
        "Status": "Qualified",
        "Conversation ID": active_evt.get("correlation_id", "conv_active"),
        "Created": "Just Now (Active Session)"
    }
    if dyn_lead["Email"] not in [l["Email"] for l in leads_list]:
        leads_list.insert(0, dyn_lead)

# Render Leads Cards
for lead in leads_list:
    st.markdown(f"""
        <div class="metric-card" style="padding: 18px; margin-bottom: 14px; border-left: 4px solid #6366F1;">
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <div>
                    <span style="font-size: 1.1rem; font-weight: 700; color: #FFFFFF;">{lead['Lead Name']}</span>
                    <span style="font-size: 0.85rem; color: #9CA3AF; margin-left: 8px;">({lead['Company']})</span>
                    <span class="badge badge-success" style="margin-left: 10px;">● {lead['Status']}</span>
                </div>
                <div style="font-size: 0.78rem; color: #94A3B8;">{lead['Created']}</div>
            </div>
            <div style="display: flex; gap: 24px; margin-top: 10px; font-size: 0.82rem; color: #D1D5DB;">
                <div><b>Email:</b> {lead['Email']}</div>
                <div><b>Phone:</b> {lead['Phone']}</div>
                <div><b>Source:</b> <span class="code-pill">{lead['Source']}</span></div>
                <div><b>Conversation ID:</b> <span class="code-pill">{lead['Conversation ID']}</span></div>
            </div>
        </div>
    """, unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)
st.subheader("📜 Attached CRM Notes & Conversation Transcripts")

with st.expander("💬 View Conversation Notes for `LEAD-2026-0001` (Sarah Connor)", expanded=True):
    st.markdown("""
        <div class="terminal-box">
            <div class="terminal-line info"><b>Kairon Chatbot Qualified Summary:</b></div>
            <div class="terminal-line success">Prospect Sarah Connor qualified for Enterprise CRM package (Cyberdyne Systems).</div>
            <div class="terminal-line">Employee Count: 150+ | Interest: Multi-tenant CRM Lead Sync & Redis Deduplication.</div>
            <div class="terminal-line warn">Dispatched via KaironEventPublisher at 2026-07-30T15:20:00Z</div>
        </div>
    """, unsafe_allow_html=True)
