providers:
  oidc:
    azure_oidc:
      required_fields:
        - tenant
        - realm_name
        - client_id
        - client_secret
    keycloak_oidc:
      required_fields:
        - realm_name
        - client_id
        - client_secret
