stages:
  - test

variables:
  UV_PYTHON: "3.10"

before_script:
  - echo "Stage Started for " $CI_COMMIT_REF_NAME
  - export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"

test:
  tags:
    - kairon-test
  stage: test
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  script:
    - chmod +x ./setup.sh
    - ./setup.sh
    - uv run pytest tests --html=report.html --cov=kairon --cov-report term --cov-report xml:coverage.xml --cov-report html:coverage_html --disable-warnings
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - report.html
      - coverage.xml
      - coverage_html/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
