

class MailConstants:
    DEFAULT_SMTP_SERVER = 'smtp.gmail.com'
    DEFAULT_IMAP_SERVER = 'imap.gmail.com'
    DEFAULT_SMTP_PORT = 587

    DEFAULT_TEMPLATE = "<p>{bot_response}</p> <br/><br/><span style='color:#999;'> Generated by kAIron AI.</span>\n"

    PROCESS_MESSAGE_BATCH_SIZE = 4

