

class MailConstants:
    DEFAULT_SMTP_SERVER = 'smtp.gmail.com'
    DEFAULT_IMAP_SERVER = 'imap.gmail.com'
    DEFAULT_SMTP_PORT = 587
    DEFAULT_LLM_TYPE = "openai"
    DEFAULT_HYPERPARAMETERS = {
        "frequency_penalty": 0,
        "logit_bias": {},
        "max_tokens": 300,
        "model": "gpt-4o-mini",
        "n": 1,
        "presence_penalty": 0,
        "stop": None,
        "stream": False,
        "temperature": 0,
        "top_p": 0
    }
    DEFAULT_TEMPLATE = "<p>Dear {name},</p> <p>{bot_response}</p> <br/><br/><span style='color:#999;'> Generated by kAIron AI.</span>\n"
    DEFAULT_SYSTEM_PROMPT = 'Classify into one of the intents and extract entities as given in the context.' \
                            'If the mail does not belong to any of the intents, classify intent as null.'

    PROCESS_MESSAGE_BATCH_SIZE = 4

