FROM python:3.7-buster

WORKDIR /app
USER root
RUN apt-get update -qq && \
python -m pip install --upgrade pip && \
python -m pip install tornado && \
python -m pip install mongoengine==0.23.1 && \
python -m pip install smart-config==0.1.3 && \
python -m pip install validators && \
python -m pip install rasa_sdk==2.1.2 && \
python -m pip install dnspython && \
python -m pip install pyjwt && \
python -m pip install elastic-apm
RUN python3 -m pip install pymongo==3.12.0


COPY kairon/actions /app/kairon/actions/
COPY kairon/shared/actions /app/kairon/shared/actions
COPY kairon/shared/accounts /app/kairon/shared/accounts
COPY kairon/shared/tornado /app/kairon/shared/tornado
COPY kairon/shared/utils.py /app/kairon/shared/
COPY system.yaml /app/

USER 1001
EXPOSE 5055
CMD ["python","-m", "kairon.actions.server"]

