FROM amazonlinux:latest

WORKDIR /app

RUN yum update -y
RUN yum -y install wget make gcc openssl-devel bzip2-devel
RUN amazon-linux-extras install python3.8
RUN rm /usr/bin/python
RUN ln -s /usr/bin/python3.8 /usr/bin/python
RUN python -m pip install --upgrade pip
RUN python -m pip install tornado
RUN python -m pip install rasa[full]==2.8.15
RUN python -m pip install mongoengine==0.23.1
RUN python -m pip install smart-config==0.1.3
RUN python -m pip install validators
RUN python -m pip install dnspython
RUN python -m pip install pydantic
RUN python -m pip install password-strength
RUN python -m pip install loguru~=0.5.3
RUN python -m pip install elastic-apm
RUN python -m pip install passlib[bcrypt]
RUN python -m pip install pymongo==3.12.0
RUN python -m pip install fastapi>=0.68.1
RUN python -m spacy download en_core_web_md
RUN python -m spacy link en_core_web_md en
RUN python -m pip install cryptography~=3.4.8
RUN python -m pip install transformers==4.5.0
RUN python -m pip install websockets==10.1
RUN python -m pip install websockets==10.1
RUN python -m pip install aiohttp==3.8.0
RUN python -m pip install numpy==1.22.0
RUN python -m pip install ujson==5.1.0
RUN python -m pip install blinker

RUN mkdir -p /home/cache
RUN chmod -R 777 /home/cache

COPY kairon/ /app/kairon
COPY metadata /app/metadata
COPY system.yaml /app/
COPY email.yaml /app/

ENV HF_HOME="/home/cache"

EXPOSE 5000
CMD ["python","-m", "kairon.chat.server","--logging=debug"]

