FROM amazonlinux:latest

SHELL ["/bin/bash", "-c"]

ENV TRANSLATOR_HOME=/app

WORKDIR ${TRANSLATOR_HOME}
RUN yum update -y
RUN yum -y install wget make gcc openssl-devel bzip2-devel
RUN amazon-linux-extras install python3.8
RUN rm /usr/bin/python
RUN ln -s /usr/bin/python3.8 /usr/bin/python
RUN python -m pip install --upgrade pip
RUN python -m pip install pyyaml
RUN python -m pip install pandas
RUN python -m pip install rasa[full]==2.8.15
RUN python -m pip install validators
RUN python -m pip install loguru
RUN python -m pip install smart-config==0.1.3
RUN python -m pip install passlib[bcrypt]
RUN python -m pip install password-strength
RUN python -m pip install elastic-apm
RUN python -m pip install fastapi>=0.68.1
RUN python -m pip install fastapi_sso
RUN python -m pip install uvicorn>=0.12.3
RUN python -m pip install websockets==10.1
RUN python -m pip install aiohttp==3.8.0
RUN python -m pip install transformers==4.23.0
RUN python -m pip install numpy==1.22.0
RUN python -m pip install blinker
RUN python -m pip install google-cloud-translate
RUN python -m pip install keybert
RUN python -m pip install bs4
RUN python -m pip install protobuf==3.20.2
RUN python -m pip install mongoengine==0.23.1
RUN python -m pip install pymongo==3.12.0
RUN python -m pip install pyjwt==2.6.0

RUN mkdir ssl
RUN chmod 777 -R /tmp

COPY kairon ${TRANSLATOR_HOME}/kairon
COPY system.yaml ${TRANSLATOR_HOME}/
COPY email.yaml ${TRANSLATOR_HOME}/
COPY metadata ${TRANSLATOR_HOME}/metadata
COPY template ${TRANSLATOR_HOME}/template
COPY augmentation ${TRANSLATOR_HOME}/augmentation

ENV BOT default
ENV USER default
ENV DEST_LANG default
ENV TRANSLATE_RESPONSES default
ENV TRANSLATE_ACTIONS default

CMD ["sh","-c","python -m kairon multilingual ${BOT} ${USER} ${DEST_LANG} ${TRANSLATE_RESPONSES} ${TRANSLATE_ACTIONS}"]
