ARG BASE_IMAGE=kairon-base:latest
FROM $BASE_IMAGE

WORKDIR ${KAIRON_HOME}

USER 1001

ENV APP_MODULE=kairon.actions.server:action

EXPOSE 5055
CMD uvicorn ${APP_MODULE} --host 0.0.0.0 --port 5055 --no-server-header --no-access-log

