FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

SHELL ["/bin/bash", "-c"]

WORKDIR /app
USER root

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install pyyaml
RUN python3 -m pip install mongoengine==0.23.1
RUN python3 -m pip install rasa[full]==2.1.2
RUN python3 -m pip install cython
RUN python3 -m pip install pandas
RUN python3 -m pip install pyjwt
RUN python3 -m pip install passlib[bcrypt]
RUN python3 -m pip install python-multipart
RUN python3 -m pip install validators
RUN python3 -m pip install secure==0.2.1
RUN python3 -m pip install password-strength
RUN python3 -m pip install loguru
RUN python3 -m pip install smart-config==0.1.3
RUN python3 -m pip install elastic-apm
RUN mkdir ssl

COPY kairon /app/kairon
COPY email.yaml /app/email.yaml
EXPOSE 8083

CMD ["uvicorn", "kairon.history.main:app","--host","0.0.0.0","--port","8083"]
