FROM amazonlinux:latest

SHELL ["/bin/bash", "-c"]

ENV KG_HOME=/app

WORKDIR ${KG_HOME}
RUN yum update -y
RUN yum -y install wget make gcc openssl-devel bzip2-devel git
RUN amazon-linux-extras install python3.8
RUN rm /usr/bin/python
RUN ln -s /usr/bin/python3.8 /usr/bin/python
RUN python -m pip install --upgrade pip
RUN python -m pip install pyyaml
RUN python -m pip install loguru
RUN python -m pip install smart-config==0.1.3
RUN python -m pip install python-docx
RUN python -m pip install PyMuPDF
RUN python -m pip install sentencepiece
RUN python -m pip install nltk==3.6.6
RUN python -m pip install torch==1.6.0
RUN python -m pip install nlp
RUN python -m pip install transformers==4.23.0
RUN python -m pip install elastic-apm
RUN mkdir ssl
RUN mkdir data_generator
RUN chmod 777 -R /tmp
RUN python -m pip install numpy==1.22.0
RUN python -m pip install ujson==5.1.0
RUN python -m pip install keybert
RUN python -m pip install bs4
RUN python -m pip install protobuf==3.20.2
RUN python -m pip install mongoengine==0.23.1
RUN python -m pip install pymongo==3.12.0
RUN python -m pip install pyjwt==2.6.0

COPY augmentation ${KG_HOME}/augmentation
COPY system.yaml ${KG_HOME}/
COPY template ${KG_HOME}/template
COPY custom ${KG_HOME}/custom
COPY email.yaml ${KG_HOME}/

ENV KAIRON_URL default
ENV USER default
ENV TYPE default
ENV WEBSITE_URL default
ENV DEPTH default

CMD ["sh","-c","python -m kairon generate-data ${BOT} ${USER} ${TYPE} ${WEBSITE_URL} ${DEPTH}"]
