ARG BASE_IMAGE=kairon-base:latest
FROM $BASE_IMAGE

ENV RASA_TELEMETRY_ENABLED=false

WORKDIR ${KAIRON_HOME}

ENV BOT default
ENV USER default
ENV TOKEN default

CMD ["sh","-c","python -m kairon train ${BOT} ${USER} ${TOKEN}"]
