FROM amazonlinux:latest

WORKDIR /app
USER root
RUN yum update -y
RUN yum -y install wget make gcc openssl-devel bzip2-devel
RUN amazon-linux-extras install python3.8
RUN rm /usr/bin/python
RUN ln -s /usr/bin/python3.8 /usr/bin/python
RUN python -m pip install --upgrade pip && \
python -m pip install tornado==6.1 && \
python -m pip install mongoengine==0.23.1 && \
python -m pip install smart-config==0.1.3 && \
python -m pip install validators && \
python -m pip install rasa==2.8.15 && \
python -m pip install dnspython && \
python -m pip install pyjwt && \
python -m pip install elastic-apm
RUN python -m pip install pymongo==3.12.0
RUN python -m pip install fastapi>=0.68.1
RUN python -m pip install fastapi_sso
RUN python -m pip install pydantic~=1.8.2
RUN python -m pip install password-strength
RUN python -m pip install passlib[bcrypt]
RUN python -m pip install cryptography~=3.4.8
RUN python -m pip install websockets==9.1
RUN python -m pip install aiohttp==3.8.0
RUN python -m pip install json2html
RUN python -m pip install numpy==1.22.0
RUN python -m pip install ujson==5.1.0
RUN python -m pip install Pillow==9.0.0
RUN python -m pip install blinker
RUN python -m pip install google-api-python-client
RUN python -m pip install cryptography
RUN python -m pip install dramatiq
RUN python -m pip install dramatiq-mongodb==0.6.1
RUN python -m pip install google-cloud-translate
RUN python -m pip install keybert
RUN python -m pip install  bs4
RUN python -m pip install mongoengine==0.23.1
RUN python -m pip install pymongo==3.12.0
RUN python -m pip install protobuf==3.20.2
RUN python -m pip install pyjwt==2.6.0
RUN python -m pip install openpyxl
RUN python -m pip install pandas
RUN python -m pip install uuid6

RUN mkdir -p /home/cache
RUN chmod -R 777 /home/cache

ENV HF_HOME="/home/cache"

COPY kairon/ /app/kairon
COPY metadata /app/metadata
COPY system.yaml /app/
COPY email.yaml /app/
COPY augmentation /app/augmentation

USER 1001
EXPOSE 5056
CMD ["python","-m", "kairon.events.server", "--logging=debug"]
