FROM amazonlinux:latest

SHELL ["/bin/bash", "-c"]

ENV IMPORTER_HOME=/app

WORKDIR ${IMPORTER_HOME}
RUN yum update -y
RUN yum -y install wget make gcc openssl-devel bzip2-devel
RUN amazon-linux-extras install python3.8
RUN rm /usr/bin/python
RUN ln -s /usr/bin/python3.8 /usr/bin/python
RUN python -m pip install --upgrade pip
RUN python -m pip install pyyaml
RUN python -m pip install rasa[full]==2.8.13
RUN python -m pip install mongoengine==0.23.1
RUN python -m pip install validators
RUN python -m pip install loguru
RUN python -m pip install smart-config==0.1.3
RUN python -m pip install passlib[bcrypt]
RUN python -m pip install password-strength
RUN python -m pip install elastic-apm
RUN python -m pip install pymongo==3.12.0
RUN python -m pip install fastapi>=0.68.1
RUN python -m pip install uvicorn>=0.12.3
RUN python3 -m pip install nlpaug
RUN python3 -m pip install torch
RUN python3 -m pip install nltk==3.6
RUN python3 -m pip install pytest
RUN python3 -m nltk.downloader wordnet
RUN python3 -m nltk.downloader averaged_perceptron_tagger
RUN mkdir ssl
RUN mkdir testing_data
RUN mkdir models
RUN chmod 777 -R /tmp

COPY kairon ${IMPORTER_HOME}/kairon
COPY system.yaml ${IMPORTER_HOME}/

ENV BOT default
ENV USER default


CMD ["sh","-c","python -m kairon test ${BOT} ${USER}"]
