FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

SHELL ["/bin/bash", "-c"]

ENV KG_HOME=/app

WORKDIR ${KG_HOME}

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install pyyaml
RUN python3 -m pip install cython
RUN python3 -m pip install pyjwt
RUN python3 -m pip install passlib[bcrypt]
RUN python3 -m pip install python-multipart
RUN python3 -m pip install validators
RUN python3 -m pip install secure
RUN python3 -m pip install spacy==2.3.2
RUN python3 -m spacy download en_core_web_md
RUN python3 -m spacy link en_core_web_md en
RUN python3 -m pip install password-strength
RUN python3 -m pip install loguru
RUN python3 -m pip install smart-config==0.1.3
RUN python3 -m pip install python-docx
RUN python3 -m pip install PyMuPDF
RUN python3 -m pip install sentencepiece
RUN python3 -m pip install git+https://github.com/sfahad1414/question_generation.git
RUN mkdir ssl
RUN mkdir data_generator
RUN chmod 777 -R /tmp

COPY augmentation ${KG_HOME}/augmentation
COPY system.yaml ${KG_HOME}/
COPY template ${KG_HOME}/template
COPY custom ${KG_HOME}/custom
COPY email.yaml ${KG_HOME}/

ENV KAIRON_URL default
ENV USER default
ENV TOKEN default

CMD ["sh","-c","python -m augmentation --generate-training-data ${KAIRON_URL} ${USER} ${TOKEN}"]