FROM amazonlinux:2.0.20240131.0

ENV RASA_NLU_DOCKER="YES" \
    RASA_NLU_HOME=/app

WORKDIR ${RASA_NLU_HOME}
RUN yum update -y
RUN yum -y install wget make gcc openssl-devel bzip2-devel
RUN amazon-linux-extras install python3.8
RUN rm /usr/bin/python
RUN ln -s /usr/bin/python3.8 /usr/bin/python
RUN python -m pip install --upgrade pip
RUN python -m pip install rasa==2.8.15
RUN python -m pip install cython
RUN python -m pip install pandas
RUN python -m pip install passlib[bcrypt]
RUN python -m pip install python-multipart
RUN python -m pip install validators
RUN python -m pip install secure
RUN python -m pip install password-strength
RUN python -m pip install loguru
RUN python -m pip install smart-config==0.1.3
RUN python -m pip install elastic-apm
RUN python -m pip install cryptography~=3.4.8
RUN python -m pip install websockets==10.1
RUN python -m pip install uvicorn>=0.18.2
RUN python -m pip install fastapi-keycloak
RUN python -m pip install fastapi==0.78.0
RUN python -m pip install aiohttp==3.8.0
RUN python -m pip install pytest
RUN python -m pip install fastapi_sso
RUN python -m pip install json2html
RUN python -m pip install blinker
RUN python -m pip install numpy==1.22.0
RUN python -m pip install ujson==5.1.0
RUN python -m pip install jira
RUN python -m pip install zenpy
RUN python -m pip install pipedrive-python-lib
RUN python -m pip install google-cloud-translate
RUN python -m pip install  bs4
RUN python -m pip install protobuf==3.20.2
RUN python -m pip install mongoengine==0.23.1
RUN python -m pip install pymongo==3.12.1
RUN python -m pip install pyjwt==2.6.0
RUN python -m pip install openpyxl
RUN python -m pip install uuid6
RUN python -m pip install croniter
RUN python -m pip install pydantic==1.10.11
RUN python -m pip install tiktoken
RUN python -m pip install validators==0.20.0
RUN python -m pip install aiohttp-retry
RUN python -m pip install pqdict

RUN mkdir ssl
RUN mkdir data_generator
RUN mkdir training_data
RUN mkdir testing_data
RUN mkdir models
RUN chmod 777 -R /tmp

COPY kairon/api ${RASA_NLU_HOME}/kairon/api
COPY kairon/chat ${RASA_NLU_HOME}/kairon/chat
COPY kairon/idp ${RASA_NLU_HOME}/kairon/idp
COPY kairon/importer ${RASA_NLU_HOME}/kairon/importer
COPY kairon/shared ${RASA_NLU_HOME}/kairon/shared
COPY kairon/importer ${RASA_NLU_HOME}/kairon/importer
COPY kairon/events ${RASA_NLU_HOME}/kairon/events
COPY kairon/live_agent ${RASA_NLU_HOME}/kairon/live_agent
COPY kairon/__init__.py ${RASA_NLU_HOME}/kairon/
COPY kairon/exceptions.py ${RASA_NLU_HOME}/kairon/

COPY system.yaml ${RASA_NLU_HOME}/
COPY template ${RASA_NLU_HOME}/template
COPY custom ${RASA_NLU_HOME}/custom
COPY email.yaml ${RASA_NLU_HOME}/
COPY metadata ${RASA_NLU_HOME}/metadata

ENV WORKER_TIMEOUT=240
ENV APP_MODULE=kairon.api.app.main:app
EXPOSE 80

CMD uvicorn ${APP_MODULE} --host 0.0.0.0 --port 80 --no-server-header
