ARG BASE_IMAGE=kairon-base:latest
FROM $BASE_IMAGE

ENV BOT default
ENV USER default
ENV TILL_DATE default
ENV SENDER_ID default


CMD ["sh","-c","python -m kairon delete-conversation ${BOT} ${USER} ${TILL_DATE} ${SENDER_ID}"]
