FROM amazonlinux:latest

ENV RASA_NLU_DOCKER="YES" \
    RASA_NLU_HOME=/app \
    RASA_NLU_PYTHON_PACKAGES=/usr/local/lib/python3.7/dist-packages

WORKDIR ${RASA_NLU_HOME}
RUN yum update -y
RUN yum -y install wget make gcc openssl-devel bzip2-devel
RUN yum -y install python37
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install rasa[full]==2.8.10
RUN python3 -m pip install mongoengine==0.23.1
RUN python3 -m pip install cython
RUN python3 -m pip install pandas
RUN python3 -m pip install passlib[bcrypt]
RUN python3 -m pip install python-multipart
RUN python3 -m pip install validators
RUN python3 -m pip install secure==0.2.1
RUN python3 -m spacy download en_core_web_md
RUN python3 -m spacy link en_core_web_md en
RUN python3 -m pip install password-strength
RUN python3 -m pip install loguru
RUN python3 -m pip install smart-config==0.1.3
RUN python3 -m pip install elastic-apm
RUN python3 -m pip install pymongo==3.12.0
RUN python3 -m pip install cryptography~=3.4.8
RUN python3 -m pip install transformers==4.5.0
RUN python3 -m pip install websockets==9.1
RUN mkdir ssl
RUN mkdir data_generator
RUN mkdir training_data
RUN chmod 777 -R /tmp

COPY kairon ${RASA_NLU_HOME}/kairon
COPY system.yaml ${RASA_NLU_HOME}/
COPY template ${RASA_NLU_HOME}/template
COPY custom ${RASA_NLU_HOME}/custom
COPY email.yaml ${RASA_NLU_HOME}/

ENV APP_MODULE=kairon.api.app.main:app
EXPOSE 80

CMD ["/start.sh"]
