ARG BASE_IMAGE=kairon-base:latest
FROM $BASE_IMAGE

WORKDIR ${KAIRON_HOME}

ENV BOT default
ENV USER default
ENV EVENT_ID default

CMD ["sh","-c","python -m kairon broadcast ${BOT} ${USER} ${EVENT_ID}"]
