ARG BASE_IMAGE=kairon-base:latest
FROM $BASE_IMAGE

ENV BOT default
ENV USER default
ENV DEST_LANG default
ENV TRANSLATE_RESPONSES default
ENV TRANSLATE_ACTIONS default

CMD ["sh","-c","python -m kairon multilingual ${BOT} ${USER} ${DEST_LANG} ${TRANSLATE_RESPONSES} ${TRANSLATE_ACTIONS}"]
