FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7-2021-06-09

SHELL ["/bin/bash", "-c"]

ENV IMPORTER_HOME=/app

WORKDIR ${IMPORTER_HOME}

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install pyyaml
RUN python3 -m pip install rasa[full]==2.1.2
RUN python3 -m pip install mongoengine==0.23.1
RUN python3 -m pip install validators
RUN python3 -m pip install loguru
RUN python3 -m pip install smart-config==0.1.3
RUN python3 -m pip install passlib[bcrypt]
RUN python3 -m pip install password-strength
RUN python3 -m pip install elastic-apm
RUN python3 -m pip install pymongo==3.12.0
RUN python3 -m pip install nlpaug
RUN python3 -m pip install torch
RUN python3 -m pip install nltk==3.6

RUN mkdir ssl
RUN mkdir testing_data
RUN mkdir models
RUN chmod 777 -R /tmp

COPY kairon ${IMPORTER_HOME}/kairon
COPY system.yaml ${IMPORTER_HOME}/

python -m nltk.downloader wordnet
python -m nltk.downloader averaged_perceptron_tagger

ENV BOT default
ENV USER default


CMD ["sh","-c","python -m kairon test ${BOT} ${USER}"]
