ARG BASE_IMAGE=kairon-base:latest
FROM $BASE_IMAGE

WORKDIR ${KAIRON_HOME}

ENV APP_MODULE=kairon.evaluator.main:app TIMEOUT=120
COPY kairon /app/kairon

EXPOSE 8087

CMD uvicorn ${APP_MODULE} --host","0.0.0.0 --port 8087 --no-server-header --no-access-log
