ARG BASE_IMAGE=kairon-base:latest
FROM $BASE_IMAGE

WORKDIR ${KAIRON_HOME}

ENV NUM_PROCESSES=1
ENV NUM_THREADS=1

EXPOSE 5057

CMD dramatiq kairon.events.broker --processes ${NUM_PROCESSES} --threads ${NUM_THREADS} --verbose
