FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7 AS base
SHELL ["/bin/bash", "-c"]

ENV RASA_NLU_DOCKER="YES" \
    RASA_NLU_HOME=/app \
    RASA_NLU_PYTHON_PACKAGES=/usr/local/lib/python3.7/dist-packages

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install nltk
RUN python3 -m pip install transformers==4.0.0
RUN python3 -m pip install loguru
RUN python3 -m pip install nlp
RUN python3 -m pip install torch
RUN python3 -m pip install git+https://github.com/sfahad1414/question_generation.git
RUN python3 -m nltk.downloader punkt

WORKDIR ${RASA_NLU_HOME}
COPY augmentation ${RASA_NLU_HOME}/augmentation
EXPOSE 8000
CMD ["uvicorn", "augmentation.question_generator.server:app","--host","0.0.0.0"]