FROM python:3.7-buster

WORKDIR /app
USER root
RUN apt-get update -qq && \
python -m pip install --upgrade pip && \
python -m pip install tornado && \
python -m pip install rasa[full]==2.1.2 && \
python -m pip install mongoengine==0.23.1 && \
python -m pip install pyjwt && \
python -m pip install spacy==2.3.2 && \
python -m spacy download en_core_web_md && \
python -m spacy link en_core_web_md en && \
python -m pip install tensorflow==2.3.2 && \
python -m pip install numpy==1.19.5 && \
python -m pip install pymongo==3.12.0 && \
python -m pip install smart-config==0.1.3 && \
python -m pip install validators && \
python -m pip install dnspython && \
python -m pip install pydantic && \
python -m pip install elastic-apm
RUN python3 -m pip install pymongo==3.12.0


COPY kairon/chat /app/kairon/chat/
COPY kairon/shared/actions /app/kairon/shared/actions
COPY kairon/shared/tornado /app/kairon/shared/tornado
COPY kairon/shared/account /app/kairon/shared/account
COPY kairon/shared/models.py /app/kairon/shared/
COPY kairon/shared/utils.py /app/kairon/shared/
COPY system.yaml /app/

USER 1001
EXPOSE 5055
CMD ["python","-m", "kairon.chat.server"]

