FROM amazonlinux:latest

SHELL ["/bin/bash", "-c"]

ENV IMPORTER_HOME=/app

WORKDIR ${IMPORTER_HOME}
RUN yum update -y
RUN yum -y install wget make gcc openssl-devel bzip2-devel
RUN amazon-linux-extras install python3.8
RUN rm /usr/bin/python
RUN ln -s /usr/bin/python3.8 /usr/bin/python
RUN python -m pip install --upgrade pip
RUN python -m pip install pyyaml
RUN python -m pip install rasa[full]==2.8.15
RUN python -m pip install mongoengine==0.23.1
RUN python -m pip install validators
RUN python -m pip install loguru
RUN python -m pip install smart-config==0.1.3
RUN python -m pip install passlib[bcrypt]
RUN python -m pip install password-strength
RUN python -m pip install elastic-apm
RUN python -m pip install pymongo==3.12.0
RUN python -m pip install fastapi>=0.68.1
RUN python -m pip install uvicorn>=0.12.3
RUN python -m pip install websockets==10.1
RUN python -m pip install aiohttp==3.8.0
RUN python -m pip install transformers==4.5.0
RUN python -m pip install blinker
RUN python -m pip install jira
RUN python -m pip install zenpy
RUN python -m pip install pipedrive-python-lib
RUN mkdir ssl
RUN mkdir training_data
RUN chmod 777 -R /tmp
RUN python -m pip install numpy==1.22.0
RUN python -m pip install ujson==5.1.0

COPY kairon ${IMPORTER_HOME}/kairon
COPY metadata /app/metadata
COPY system.yaml ${IMPORTER_HOME}/

ENV BOT default
ENV USER default
ENV IMPORT_DATA default
ENV OVERWRITE default


CMD ["sh","-c","python -m kairon data-importer ${BOT} ${USER} ${IMPORT_DATA} ${OVERWRITE}"]
