config:
  api_server_host_url: https://kairon-api.nimblework.com
  botClassName: ''
  buttonType: button
  chatContainerClassName: ''
  chat_server_base_url: https://kairon-chat.nimblework.com/
  container: '#root'
  containerClassName: ''
  formClassName: ''
  headerClassName: ''
  name: kairon
  openButtonClassName: ''
  styles:
    botStyle:
      backgroundColor: '#e0e0e0'
      color: '#000000'
      fontFamily: '''Roboto'', sans-serif'
      fontSize: 14px
      iconSrc: ''
      showIcon: 'false'
    buttonStyle:
      backgroundColor: '#2b3595'
      color: '#ffffff'
    containerStyles:
      background: '#ffffff'
      height: 500px
      width: 350px
    headerStyle:
      backgroundColor: '#2b3595'
      color: '#ffffff'
      height: 60px
    userStyle:
      backgroundColor: '#2b3595'
      color: '#ffffff'
      fontFamily: '''Roboto'', sans-serif'
      fontSize: 14px
      iconSrc: ''
      showIcon: 'false'
  userClassName: ''
  userStorage: ls
  userType: custom
  welcomeMessage: Hello! How are you?
  whitelist:
  - '*'
